version: '3.8'

services:
  camera-report:
    build: .
    container_name: camera-work-auto-report
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"