name: Daily Report

on:
  schedule:
    # 한국시간 오전 10시 = UTC 오전 1시
    # 평일(화-금) 오전 10시에 실행 (월요일은 주간/월간 보고서가 있으므로 제외)
    - cron: '0 1 * * 2-5'  # 화-금
  workflow_dispatch:

jobs:
  daily-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Log execution time
      run: |
        KST_TIME=$(TZ='Asia/Seoul' date '+%Y-%m-%d %H:%M:%S')
        echo "Running daily report at: $KST_TIME KST"
    
    - name: Generate daily report
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        SLACK_DM_USER_IDS: ${{ secrets.SLACK_DM_USER_IDS }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        echo "Generating daily report..."
        node dist/generate-report.js --type daily