name: Daily Report # main 브랜치의 이름 사용

on:
  schedule:
    # 'aiden/auto-report-system' 브랜치의 매일 실행 스케줄 사용
    - cron: '0 1 * * *'  # UTC 01:00 = KST 10:00
  workflow_dispatch:

jobs:
  daily-report: # main 브랜치의 job 이름 사용
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Generate daily report # main 브랜치의 핵심 로직(Slack, Supabase 연동) 사용
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        SLACK_DM_USER_IDS: ${{ secrets.SLACK_DM_USER_IDS }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: node dist/generate-report.js daily