name: Monthly Weekly Report

on:
  schedule:
    - cron: '0 1 1-7 * 2'  # 매월 첫째 주 화요일 10:00 AM KST (UTC+9)
  workflow_dispatch:

jobs:
  monthly-weekly-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Generate monthly-weekly report
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        SLACK_DM_USER_IDS: ${{ secrets.SLACK_DM_USER_IDS }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: node dist/src/generate-report.js monthly-weekly