name: Retry Report on Failure

on:
  workflow_run:
    workflows: ["Daily Camera Report"]
    types:
      - completed

jobs:
  retry-if-failed:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
    - name: Wait before retry
      run: sleep 3600  # 1시간 대기
    
    - name: Trigger retry
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'daily-report.yml',
            ref: 'main'
          })
          console.log('Retry triggered after failure')