name: Test Run

on:
  workflow_dispatch:  # 수동 실행 전용

jobs:
  test-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Test Firebase connection
      timeout-minutes: 5
      run: |
        echo "Testing Firebase connection..."
        node -e "
        const { FirebaseDataFetcher } = require('./dist/services/firebaseDataFetcher');
        (async () => {
          const fetcher = FirebaseDataFetcher.getInstance();
          const tasks = await fetcher.fetchCameraTasks();
          console.log('✅ Firebase 연결 성공: ' + tasks.length + '개 업무 발견');
        })().catch(err => {
          console.error('❌ Firebase 연결 실패:', err.message);
          process.exit(1);
        });
        "
    
    - name: Test API keys
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "Checking API keys..."
        if [ -z "$GEMINI_API_KEY" ]; then
          echo "❌ GEMINI_API_KEY is not set"
          exit 1
        else
          echo "✅ GEMINI_API_KEY is set"
        fi
        
        if [ -z "$GOOGLE_SERVICE_ACCOUNT_KEY" ]; then
          echo "❌ GOOGLE_SERVICE_ACCOUNT_KEY is not set"
          exit 1
        else
          echo "✅ GOOGLE_SERVICE_ACCOUNT_KEY is set"
          # Check if it's valid JSON
          echo "$GOOGLE_SERVICE_ACCOUNT_KEY" | jq -e . >/dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "✅ GOOGLE_SERVICE_ACCOUNT_KEY is valid JSON"
          else
            echo "❌ GOOGLE_SERVICE_ACCOUNT_KEY is not valid JSON"
            exit 1
          fi
        fi
    
    - name: Run full test
      timeout-minutes: 10
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        GOOGLE_DOC_ID: 1QvLn7yJJ1c3xtwF8bd4lK_k6FL4hmcT5TiGvoeGRPow
        TZ: Asia/Seoul
      run: |
        echo "Running full system test with 10-minute timeout..."
        timeout 600s npm start -- --run-once || {
          echo "❌ 테스트가 10분을 초과하여 중단됨"
          exit 1
        }
    
    - name: Report results
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ 테스트 성공!"
          echo "Google Docs를 확인해주세요: https://docs.google.com/document/d/1QvLn7yJJ1c3xtwF8bd4lK_k6FL4hmcT5TiGvoeGRPow/edit"
        else
          echo "❌ 테스트 실패. 로그를 확인해주세요."
        fi