name: Weekly Report

on:
  schedule:
    - cron: '10 1 * * 1'  # 매주 월요일 10:10 AM KST (UTC+9)
  workflow_dispatch:

jobs:
  weekly-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Check if first Monday of month
      id: check-first-monday
      run: |
        current_date=$(date +%d)
        if [ $current_date -le 7 ]; then
          echo "is_first_monday=true" >> $GITHUB_OUTPUT
        else
          echo "is_first_monday=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Generate weekly report
      if: steps.check-first-monday.outputs.is_first_monday == 'false'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        SLACK_DM_USER_IDS: ${{ secrets.SLACK_DM_USER_IDS }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: node dist/generate-report.js weekly